


```{r Load Libraries, warning=FALSE, message=FALSE}
library(R.matlab)
library(purrr)
library(tidyverse)
```


```{r Prepare Names and dataframes}
overview_names <- c("TribometerNumber", "EnableLog", "Sample", "SampleID", "Project", "Countersample", "Load", "Date", "Stroke", "Velocity", "User", "Environment", "OtherDetails", "L", "W", "H", "initialmass", "initialmassWithHolder", "initialReferenceMass", "density", "Major1", "Percent1", "Minor2", "Percent2", "Minor3", "Percent3", "Minor4", "Percent4", "Minor5", "Percent5", "Minor6", "Percent6")

data_names <- c("Experiment", "CompleteLog", "TestCycles", "TotalCycles", "TestStroke", "TestDistance", "TotalDistance", "Date", "mass", "umass", "massWithHolder", "referenceMass", "V", "uV", "Fn", "FnStd", "FnD", "uFnD", "mu", "muStd", "KtotalMonte", "UKMonteTotal", "BKMonteTotal", "KtestMonteN2", "UKMonteN2", "BMonteN2", "KtestMonteN3", "UKMonteN3", "BMonteN3", "KtestMonteN4", "UKMonteN4", "BMonteN4","KtestMonteN5", "UKMonteN5", "BMonteN5", "uFn", "ud", "T", "x_RH", "x_O2", "Experiment_Name")

averagePlusStd_names <- c("time", "Fn1", "Ff1", "Humidity", "X", "MotorRev", "mu1", "time_std", "Fn1_std", "Ff1_std",      "Humidity_std", "X_std", "MotorRev_std", "mu1_std", "Experiment_Name")

data_df <- data.frame(matrix(ncol = 41, nrow = 0))
overview_df <- data.frame(matrix(ncol = 32, nrow = 0))
averagePlusStd_df <- data.frame(matrix(ncol = 15, nrow = 0))


# Create an empty list to store dataframes
all_dataframes <- list()
```


```{r}
# Specify the path to your folder
folder_path <- "./Mat_files"

# Get the list of file names in the folder
file_names <- list.files(folder_path, full.names = TRUE)

# Loop through each file and read it into a dataframe
for (file in file_names) {
  mat_file <- readMat(file)
  name_part <- sub("Mat2.mat", "", basename(file)) # Extract "Mn20"or name of experiment
  # APS extraction and conversion
  data <- as.data.frame(mat_file[["loaded.data"]][[1]][[6]]) #Use it to extract average Plus Stnd List form
  # Extract the data from list to a matrix
  holder <- matrix(nrow  = dim(data[1])-1, ncol = 14)
  for (i in 1:14) {
    for (j in 2:dim(data)[1]) {
      holder[j-1, i] <- as.numeric(data[[j, i]])
    }
  }
  # Convert matrix to data frame and add a column with the experiment name
  holder_df <-as.data.frame(holder) %>% 
    mutate(V15 = name_part) 
  colnames(holder_df) <- names(averagePlusStd_df)
  # Add to master APS df
  averagePlusStd_df <- rbind(averagePlusStd_df, holder_df)
  
  # Overview Extraction and conversion
  overview_list <- mat_file[["overview.cell"]]
  # Flatten the nested list
  flattened_list <- map(overview_list, ~.[[1]])
  # Convert the flattened list to a data frame
  flat_df <- as.data.frame(flattened_list, stringsAsFactors = FALSE)
  colnames(flat_df) <- names(overview_df)
  # Add to master overview df
  overview_df <- rbind(overview_df, flat_df)
  
  # data Extraction and conversion
  
  holder <- matrix(nrow  = 14, ncol = 40)
  for (j in 1:40) {
    for (i in 1:14) {
      holder[i, j] <- as.numeric(mat_file[["data.cell"]][[i,j]])
    }
  }
  holder_df <- as.data.frame(holder) %>% 
    mutate(V41 = name_part)
  colnames(holder_df) <- names(data_df)
  # Add to master data df
  data_df <- rbind(data_df, holder_df)
}

```


```{r Set DF Names}
colnames(averagePlusStd_df) <- averagePlusStd_names
colnames(overview_df) <- overview_names
colnames(data_df) <- data_names
```


```{r Save read RDS files}
saveRDS(averagePlusStd_df, file = "./RDS_files/averagePlusStd_df.rds")
saveRDS(overview_df, file = "./RDS_files/overview_df.rds")
saveRDS(data_df, file = "./RDS_files/data_df.rds")
APS <-readRDS(file = "./RDS_files/averagePlusStd_df.rds")
Overview <- readRDS(file = "./RDS_files/overview_df.rds")
Data <- readRDS(file = "./RDS_files/data_df.rds")
```


$V_{loss} = \frac{m_{loss}}{\frac{m_{initial}}{LWH}}$

$\sigma_V = \sqrt{\left(\frac{1}{\frac{m_{initial}}{LWH}} \sigma_{m_{\text{loss}}}\right)^2 + \left(\frac{-m_{\text{loss}}}{\frac{m_{initial}^2}{LWH}} \sigma_{m_{initial}}\right)^2  + \left(\frac{m_{\text{loss}}}{\frac{m_{initial}}{WH}} \sigma_{L}\right)^2 + \left(\frac{m_{\text{loss}}}{\frac{m_{initial}}{LH}} \sigma_{W}\right)^2+ \left(\frac{m_{\text{loss}}}{\frac{m_{initial}}{LW}} \sigma_{H}\right)^2}$

```{r}
# Needs to add best estimates (usually mean of sample) for L, W, H, m_initial, and m_loss
# Needs to either calculate uncertainty values (using CI and calculated sample stdev) or possibly take the mean of the reported uncertainty values in the data set.
sigma_m_initial <-
sigma_m_loss <-
sigma_L <-
sigma_W <-
sigma_H <-
L <-
H <-
W <-
m_initial <-
m_loss <-
sigma_V <- sqrt((sigma_m_loss / (m_initial / (L*W*H)))^2 + 
                  ((-m_loss*sigma_m_initial) / (m_initial^2 / (L*W*H)))^2 + 
                  ((m_loss*sigma_L) / (m_initial / (W*H)))^2 + 
                  ((m_loss*sigma_W) / (m_initial / (L*H)))^2 + 
                  ((m_loss*sigma_H) / (m_initial / (L*W)))^2)
```



